CREATE TABLE hosts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE metrics (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  host_id INT UNSIGNED NOT NULL,
  ts TIMESTAMP NOT NULL,
  cpu_percent DECIMAL(5,2) NOT NULL,
  ram_used_mb INT UNSIGNED NOT NULL,
  ram_total_mb INT UNSIGNED NOT NULL,
  FOREIGN KEY (host_id) REFERENCES hosts(id),
  INDEX idx_host_ts (host_id, ts)
);